language: node_js
node_js:
  - node
  - 4
  - 5
  - 6
  - 7

before_install:
  - export PATH=./node_modules/.bin:$PATH

install:
  - npm install
  - bower install

before_script:
  - pulp build

script:
  - pulp test
