language: node_js
node_js:
  - node
  - 4
  - 5
  - 6
  - 7

# disabled until travis supports mongodb ~3.4
# services:
#   - mongodb

before_install:
  - export PATH=./node_modules/.bin:$PATH

install:
  - npm install
  - bower install

before_script:
  - npm run build
# disabled until travis supports mongodb ~3.4
#  - npm run before:test

script:
  - pulp test
# disabled until travis supports mongodb ~3.4
# - npm test

after_script:
  - npm run before:release
  - npm run release

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    skip_cleanup: true
    file_glob: true
    file: releases/github/*
    on:
      tags: true
      branch: master

  - provider: npm
    api_key: $NPM_TOKEN
    email: matthias.benkort@gmail.com
    skip_cleanup: true
    on:
      tags: true
      branch: master

  - provider: pages
    github_token: $GITHUB_TOKEN
    skip_cleanup: true
    local_dir: releases/gh-pages
    on:
      tags: true
      branch: master
